language: node_js
node_js:
  - '8'
  - '10'
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - yarn run lerna run prepublish
script:
  - yarn test
before_deploy:
  - git config --global user.email ${GH_EMAIL}
  - git config --global user.name ${GH_USER}
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/geut/lerna-travis-demo.git" > /dev/null 2>&1
  - git checkout release
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - git status
  - pwd
  - ls -l
deploy:
  provider: script
  script: "npm run lerna:publish"
  skip_cleanup: true
  on:
    node: "8"
    branch: release
